package net.bitacademy.java41.servlets;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.GenericServlet;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import net.bitacademy.java41.vo.Member;

@WebServlet("/main")
@SuppressWarnings("serial")
public class MainServlet extends GenericServlet {

	@Override
	public void service(ServletRequest request, ServletResponse response)
			throws ServletException, IOException {
		//Member member  = (Member)request.getAttribute("member");
		HttpSession session = ((HttpServletRequest)request).getSession();
		Member member = (Member)session.getAttribute("member");
		
		response.setContentType("text/html;charset=UTF-8");
		PrintWriter out = response.getWriter();
		/*
		out.println("<!DOCTYPE html>");
		out.println("");
		out.println("");
		out.println("<html lang=\"en\">");
		out.println("");
		out.println("  <head>");
		out.println("");
		out.println("    <meta charset=\"utf-8\">");
		out.println("");
		out.println("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
		out.println("");
		out.println("    <meta name=\"description\" content=\"\">");
		out.println("");
		out.println("    <meta name=\"author\" content=\"\">");
		out.println("");
		out.println("    <link rel=\"shortcut icon\" href=\"../assets/ico/favicon.png\">");
		out.println("");
		out.println("");
		out.println("    <title>JJK Project - Main</title>");
		out.println("");
		out.println("");
		out.println("    <!-- Bootstrap core CSS -->");
		out.println("");
		out.println("    <link href=\"../dist/css/bootstrap.css\" rel=\"stylesheet\">");
		out.println("");
		out.println("");
		out.println("    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->");
		out.println("");
		out.println("    <!--[if lt IE 9]>");
		out.println("");
		out.println("      <script src=\"../assets/js/html5shiv.js\"></script>");
		out.println("");
		out.println("      <script src=\"../assets/js/respond.min.js\"></script>");
		out.println("");
		out.println("    <![endif]-->");
		out.println("");
		out.println("");
		out.println("    <!-- Custom styles for this template -->");
		out.println("");
		out.println("    <link href=\"carousel.css\" rel=\"stylesheet\">");
		out.println("");
		out.println("  </head>");
		out.println("");
		out.println("<!-- NAVBAR");
		out.println("");
		out.println("================================================== -->");
		out.println("");
		out.println("  <body>");
		out.println("");
		out.println("    <div class=\"navbar-wrapper\">");
		out.println("");
		out.println("      <div class=\"container\">");
		out.println("");
		out.println("");
		out.println("        <div class=\"navbar navbar-inverse navbar-static-top\">");
		out.println("");
		out.println("          <div class=\"container\">");
		out.println("");
		out.println("            <div class=\"navbar-header\">");
		out.println("");
		out.println("              <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">");
		out.println("");
		out.println("                <span class=\"icon-bar\"></span>");
		out.println("");
		out.println("                <span class=\"icon-bar\"></span>");
		out.println("");
		out.println("                <span class=\"icon-bar\"></span>");
		out.println("");
		out.println("              </button>");
		out.println("");
		out.println("              <a class=\"navbar-brand\" href=\"#\">JJK Project</a>");
		out.println("");
		out.println("            </div>");
		out.println("");
		out.println("            <div class=\"navbar-collapse collapse\">");
		out.println("");
		out.println("              <ul class=\"nav navbar-nav\">");
		out.println("");
		out.println("                <li class=\"active\"><a href=\"#\">Home</a></li>");
		out.println("");
		out.println("                <li><a href=\"#about\">About</a></li>");
		out.println("");
		out.println("                <li><a href=\"#contact\">Contact</a></li>");
		out.println("");
		out.println("                <!--<li class=\"dropdown\">");
		out.println("");
		out.println("                  <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Dropdown <b class=\"caret\"></b></a>");
		out.println("");
		out.println("                    <ul class=\"dropdown-menu\">");
		out.println("");
		out.println("                    <li><a href=\"#\">Action</a></li>");
		out.println("");
		out.println("                    <li><a href=\"#\">Another action</a></li>");
		out.println("");
		out.println("                    <li><a href=\"#\">Something else here</a></li>");
		out.println("");
		out.println("                    <li class=\"divider\"></li>");
		out.println("");
		out.println("                    <li class=\"dropdown-header\">Nav header</li>");
		out.println("");
		out.println("                    <li><a href=\"#\">Separated link</a></li>");
		out.println("");
		out.println("                    <li><a href=\"#\">One more separated link</a></li>");
		out.println("");
		out.println("                  </ul>");
		out.println("");
		out.println("                </li>-->");
		out.println("");
		out.println("              </ul>");
		out.println("");
		out.println("              ");
		out.println("");
		out.println("              ");
		out.println("");
		out.println("            </div>");
		out.println("");
		out.println("          </div>");
		out.println("");
		out.println("        </div>");
		out.println("");
		out.println("");
		out.println("      </div>");
		out.println("");
		out.println("    </div>");
		out.println("");
		out.println("");
		out.println("");
		out.println("    <!-- Carousel");
		out.println("");
		out.println("    ================================================== -->");
		out.println("");
		out.println("    <div id=\"myCarousel\" class=\"carousel slide\">");
		out.println("");
		out.println("      <!-- Indicators -->");
		out.println("");
		out.println("      <ol class=\"carousel-indicators\">");
		out.println("");
		out.println("        <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>");
		out.println("");
		out.println("        <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>");
		out.println("");
		out.println("        <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>");
		out.println("");
		out.println("      </ol>");
		out.println("");
		out.println("      <div class=\"carousel-inner\">");
		out.println("");
		out.println("        <div class=\"item active\">");
		out.println("");
		out.println("          <img src=\"data:image/png;base64,\" data-src=\"holder.js/900x500/auto/#777:#7a7a7a/text:First slide\"alt=\"First slide\">");
		out.println("");
		out.println("          <div class=\"container\">");
		out.println("");
		out.println("            <div class=\"carousel-caption\">");
		out.println("");
		out.println("              <h1>JJK 프로젝트를 소개합니다.</h1>");
		out.println("");
		out.println("              <p>JJK 프로젝트를 통해 잊을 수 없는 웹 경험을 만나보세요!</p>");
		out.println("");
		out.println("              <p><a class=\"btn btn-large btn-primary\" href=\"#\" role=\"button\">Sign up today</a></p>");
		out.println("");
		out.println("            </div>");
		out.println("");
		out.println("          </div>");
		out.println("");
		out.println("        </div>");
		out.println("");
		out.println("        <div class=\"item\">");
		out.println("");
		out.println("          <img src=\"data:image/png;base64,\" data-src=\"holder.js/900x500/auto/#666:#6a6a6a/text:Second slide\" alt=\"Second slide\">");
		out.println("");
		out.println("          <div class=\"container\">");
		out.println("");
		out.println("            <div class=\"carousel-caption\">");
		out.println("");
		out.println("              <h1>JJK 프로젝트란 무엇인가요?</h1>");
		out.println("");
		out.println("              <p>JJK 프로젝트란 빅데이터를 기반으로 고객들에게 <br>데이터마이닝 정보를 제공하는 프로젝트입니다.</p>");
		out.println("");
		out.println("              <p><a class=\"btn btn-large btn-primary\" href=\"#\" role=\"button\">Learn more</a></p>");
		out.println("");
		out.println("            </div>");
		out.println("");
		out.println("          </div>");
		out.println("");
		out.println("        </div>");
		out.println("");
		out.println("        <div class=\"item\">");
		out.println("");
		out.println("          <img src=\"data:image/png;base64,\" data-src=\"holder.js/900x500/auto/#555:#5a5a5a/text:Third slide\"alt=\"Third slide\">");
		out.println("");
		out.println("          <div class=\"container\">");
		out.println("");
		out.println("            <div class=\"carousel-caption\">");
		out.println("");
		out.println("              <h1>무엇을 망설이나요?</h1>");
		out.println("");
		out.println("              <p>세계 최고의 데이터마이닝 서비스를 경험해보세요!</p>");
		out.println("");
		out.println("              <p><a class=\"btn btn-large btn-primary\" href=\"#\" role=\"button\">Browse gallery</a></p>");
		out.println("");
		out.println("            </div>");
		out.println("");
		out.println("          </div>");
		out.println("");
		out.println("        </div>");
		out.println("");
		out.println("      </div>");
		out.println("");
		out.println("      <a class=\"left carousel-control\" href=\"#myCarousel\" data-slide=\"prev\"><span class=\"glyphicon glyphicon-chevron-left\"></span></a>");
		out.println("");
		out.println("      <a class=\"right carousel-control\" href=\"#myCarousel\" data-slide=\"next\"><span class=\"glyphicon glyphicon-chevron-right\"></span></a>");
		out.println("");
		out.println("    </div><!-- /.carousel -->");
		out.println("");
		out.println("");
		out.println("");
		out.println("");
		out.println("    ");
		out.println("");
		out.println("");
		out.println("      <!-- FOOTER -->");
		out.println("");
		out.println("      <footer>");
		out.println("");
		out.println("        <p class=\"pull-right\"><a href=\"#\">Back to top</a></p>");
		out.println("");
		out.println("        <p>&copy; 2013 Company, Inc. &middot; <a href=\"#\">Privacy</a> &middot; <a href=\"#\">Terms</a></p>");
		out.println("");
		out.println("      </footer>");
		out.println("");
		out.println("");
		out.println("   <!-- /.container -->");
		out.println("");
		out.println("");
		out.println("");
		out.println("    <!-- Bootstrap core JavaScript");
		out.println("");
		out.println("    ================================================== -->");
		out.println("");
		out.println("    <!-- Placed at the end of the document so the pages load faster -->");
		out.println("");
		out.println("    <script src=\"../assets/js/jquery.js\"></script>");
		out.println("");
		out.println("    <script src=\"../dist/js/bootstrap.min.js\"></script>");
		out.println("");
		out.println("    <script src=\"../assets/js/holder.js\"></script>");
		out.println("");
		out.println("  </body>");
		out.println("");
		out.println("</html>");
		
		*/
		out.println("<html><head><title>메인</title></head>");
		out.println("<body>");
		out.println("<td align=\"center\"><h1>로그인 성공.<br> 메인 화면으로 이동합니다.</h1>");
		out.println("<p>이메일:" + member.getEmail() + "<br>" 
				+ "이름:" + member.getName() + "<br>"
				+ "전화:" + member.getTel() + "</p>"
				+ "</td></body></html>");
		out.println("</body>");
		out.println("</html>");
		out.println(
				"<meta http-equiv='Refresh' content='2;url=../jjl/auth/main.html'>"
				+ "</head>");
	
		
	}

}
